version: "3"

services:
  postgres:
    image: postgres
    container_name: course_loopack_4
    volumes:
      - ./postgres:/postgres
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
